### PR TITLE
Update proposed-decisions.md

### PR DESCRIPTION
**Pull request by MarcelUntied**
Small changes based on earlier discussions within steering committee

### CODE REVIEW

**Review by eliashassing154 — COMMENTED** [review]
I don't see how there **can** be an entitlement but no longer **should** be one. Isn't this required before anything happens downstream? What's the reasoning here?

**Comment by MarcelUntied** [comment]
There will be an entitlement, but based on the business model of the LA this can be done upfront or after (first) access

**Comment by eliashassing154** [comment]
But that implies that links are not going to be automatically pushed (e.g. to LMS), which thus will not solve the link placement, validation and removal problems. I think the entitlement is imperative upfront, whether you decide to postpone request for payment is a different matter.

**Review by eliashassing154 — APPROVED** [review]
As discussed, approved with objections and the possibility to revert to **can.** after pilot testing.

**Pull request merged**
