### PR TITLE
Update proposed-decisions.md

### PR DESCRIPTION
**Pull request by MarcelUntied**
Added proposed decision on LML

### CODE REVIEW

**Review by cliftonc — APPROVED** [review]
Looks fine

**Comment by Joyce-OE** [comment]
I don't understand why the role of LML is now explicitly mentioned. Yesterday we had a discussion about what does / does not belong in the ecosystem. LML is not the only part, the use of digital teaching materials (by a student) for example could also belong to the Ecosystem.

**Review by eliashassing154 — APPROVED** [review]

**Comment by eliashassing154** [comment]
@Joyce-OE it's mentioned because we'll need to clarify what we're including or excluding. We discussed it in this morning's steering committee and agreed to keep working on the proposed decisions, so I imagine usage of digital products will also end up in here.

**Comment by eliashassing154** [comment]
And to clarify my previous comment: part of the ecosystem does not mean part of the pilot scope

**Pull request merged**
